const neighborhood = [
  "Boa Vista",
  "Bom Pastor",
  "Centro",
  "Granbery",
  "Jardim Glória",
  "Santa Helena",
  "São Mateus",
  "Teixeiras",
  "Dom Bosco",
  "Bairu",
  "Bonfim",
  "Botanágua",
  "Centenário",
  "Cesário Alvim",
  "Grajaú",
  "Linhares",
  "Manoel Honório",
  "Marumbi",
  "Nossa Senhora Aparecida / Meggliolário",
  "Progresso",
  "Santa Paula",
  "Santa Rita",
  "Santa Cândida",
  "São Benedito",
  "São Bernardo",
  "Vitorino Braga",
  "Eldorado",
  "Granjas Betânea",
  "Jardim Bom Clima",
  "Mariano Procópio",
  "Grama",
  "Jardim Emaús",
  "Recanto dos Lagos",
  "Parque Independência",
  "Santa Therezinha",
  "Filgueiras",
  "Vale dos Bandeirantes",
  "Parque Guarani",
  "Vila Montanhesa",
  "Araújo",
  "Barbosa Lage",
  "Barreira do Triunfo",
  "Benfica",
  "Cidade do Sol",
  "Parque das Torres",
  "Jóquei Clube II",
  "Jóquei Clube III",
  "Milho Branco",
  "Carlos Chagas",
  "Chapéu D'uvas",
  "Cerâmica",
  "Esplanada",
  "Francisco Bernardino",
  "Industrial",
  "Jardim Natal",
  "Jardim São João (Juiz de Fora)",
  "Jóquei Clube",
  "Monte Castelo",
  "Nova Benfica",
  "Nova Era",
  "Paula Lima",
  "Remonta",
  "Represa",
  "Santa Cruz",
  "São Francisco de Paula",
  "São Judas Tadeu",
  "São Dimas",
  "Vila Esperança",
  "Vila Esperança 2",
  "Aeroporto",
  "Borboleta",
  "Cruzeiro Santo Antônio",
  "Marilândia",
  "Martelos",
  "Morro do Imperador",
  "Nova Califórnia",
  "Novo Horizonte",
  "São Pedro",
  "Serro Azul",
  "Santos Dumont",
  "Nova Germânia",
  "Barão do Retiro",
  "Floresta",
  "Jardim Esperança",
  "Terras Altas",
  "Nossa Senhora de Lourdes",
  "Santo Antônio",
  "Vila Furtado de Menezes",
  "Vila Olavo Costa",
  "Niterói",
  "Costa Carvalho",
  "Bomba de Fogo",
  "Cascatinha",
  "Cruzeiro do Sul",
  "Graminha",
  "Ipiranga",
  "Jardim Laranjeiras",
  "Sagrado Coração de Jesus",
  "Salvaterra",
  "Santa Efigênia",
  "Santa Luzia",
  "São Geraldo",
  "Previdenciários",
];

export default neighborhood;
